name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: make

      - name: Install valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Run Valgrind leak check
        run: |
          while read -r cmd || [ -n "$cmd" ]; do
            echo "$cmd" | valgrind --leak-check=full --show-leak-kinds=definite,indirect,possible --track-origins=yes --trace-children=yes --track-fds=yes --error-exitcode=1 ./minishell
          done < tests/ci_commands.txt

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: make
      - name: Compare outputs
        shell: bash
        run: |
          : > minishell_out.txt
          : > bash_out.txt
          set +e
          while IFS= read -r cmd || [ -n "$cmd" ]; do
            printf '--- CMD: %s ---\n' "$cmd" >> minishell_out.txt
            printf '%s\n' "$cmd" | ./minishell >> minishell_out.txt 2>&1 || true
            printf '--- CMD: %s ---\n' "$cmd" >> bash_out.txt
            printf '%s\n' "$cmd" | bash >> bash_out.txt 2>&1 || true
          done < tests/ci_commands.txt
          diff -u minishell_out.txt bash_out.txt
